### ISSUE TITLE
Debug Drawing utils

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/renderer#28]
## Description
We implemented a Debug Drawer module that currently is capable of drawing wireframes of various primitives. However, we're missing the functionality to draw these primitives as solid objects, Python bindings to expose this module to Python, and related documentation of this module.

## Tasks
- [ ] Implementation of solid primitives using instancing
- [ ] Implementation of Python bindings
- [ ] Examples of usage (Python)
- [ ] Documentation (API auto-generated using Sphinx)
- [ ] Documentation (.rst custom made)
