### ISSUE TITLE
FrameBuffer Abstraction

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/renderer#34]
## Description
This keeps track of the FBO implementation, which would allow us to handle `off-screen rendering`, and `shadow mapping`. We should also move this component to a separate `renderer/opengl` folder.

## Tasks
- [ ] Implementation (C++)
- [ ] Examples of usage (C++)
- [ ] Integration with headless mode
- [ ] Python bindings
- [ ] Examples of usage (Python)
- [ ] Documentation (API auto-generated by Sphinx)
- [ ] Documentation (.rst custom made detailed description)
