### ISSUE TITLE
Skybox Abstraction

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/renderer#36]
## Description

This keeps track of the implementation of Skyboxes. This is a core engine object and should be abstracted from its internal implementation (e.g. OpenGL)

## Tasks

- [ ] CubeTexture implementation (C++)
- [ ] Skybox implementation (C++)
- [ ] Example of usage (C++)
- [ ] Python bindings
- [ ] Example of usage (Python)
- [ ] Documentation (API auto-generated using Sphinx and Breathe)
- [ ] Documentation (.rst custom made for a detailed description)
