### ISSUE TITLE
Reflections

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/renderer#37]
## Description

This keeps track of the implementation of plane reflections and screen space reflections. This feature is required to make the scenes look as similar as possible to the ones generated by the MuJoCo renderer.

## Tasks

- [ ] Implement stencil buffer type (C++)
- [ ] Implement plane reflections (C++)
- [ ] Example of usage (C++)
- [ ] Python bindings
- [ ] Example of usage (Python)
- [ ] Documentation (API auto-generated using Sphinx and Breathe)
- [ ] Documentation (.rst custom made for a detailed description)

## Notes

- Check the usage of the Stencil Buffer in MuJoCo plane reflections [implementation][0]

[0]: <https://github.com/deepmind/mujoco/blob/8efb04eb793bd255a4da4d9a2a3888bdde0ef004/src/render/render_gl3.c#L850> (ref-mujoco-reflection-impl)
