### ISSUE TITLE
Text rendering

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/renderer#38]
## Description

This keeps track of the rendering text of any font in the 3d scene. There are two approaches we could follow. The first is drawing like bitmaps (we would require a special font file with the related texture atlas). The second approach makes use of FreeType and a more kind of modern approach. The one implemented in MuJoCo is the first one, so for the first implementation, we could use their font texture atlases.

## Tasks

- [ ] Classic font rendering approach implementation (C++)
- [ ] Example of usage (C++)
- [ ] Modern font rendering approach (using FreeType) (C++)
- [ ] Example of usage (C++)
- [ ] Python bindings
- [ ] Example of usage (Python)
- [ ] Documentation (API auto-generated using Sphinx and Breathe)
- [ ] Documentation (.rst custom made for a detailed description)

## Notes

- Could use `stb_font` as an initial option
- Should favor the usage of FreeType
