### ISSUE TITLE
Renderer Abstraction

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/renderer#39]
## Description

This module is in charge of exposing all available features into an abstract renderer interface. It should be similar to ThreeJS. We should have a similar `ShadderLib` and `ShaderChunk` system to generate a **`Master Shader`** used for the rendering process, without requiring that many state changes if possible.

## Tasks

- [ ] Design the whole renderer module
- [ ] Implement `ShaderChunk` module (C++)
- [ ] Implement `ShaderLib` module (C++)
- [ ] Implement render pipeline (should support multiple lights and shadows) (C++)
- [ ] Examples of usage (C++)
- [ ] Python bindings
- [ ] Examples of usage (Python)
- [ ] Documentation (API auto-generated using Sphinx + Breathe)
- [ ] Documentation (.rst custom made for a detailed description)

## Notes

- Should abstract away the renderer interface from the specific graphics API (e.g. OpenGL), similar to how ThreeJS handles WebGL, WebGL2, and WebGPU. We should move all graphics-API-specific objects to their own folder.
