### ISSUE TITLE
Shader Manager Implementation

### ISSUE THREAD

**Issue by wpumacay** [wpumacay/renderer#4]
# Description

This tracks the implementation of the `shader_manager` singleton, used to both `create` and `store` shaders in a easier way. The rationale is that `shaders` will be considered as assets, and this manager will be in charge of easily create them and share the ownership of this shaders with user code that might request them.

## Tasks
- [ ] Implementatio of the **`sbader_manager`**
- [ ] Create an **`example`** of its usage
- [ ] Implement some **`unittests`**
- [ ] Implement **`python`** bindings
- [ ] Make **`documentation`** explaining its usage

## Notes
* There's the legacy implementation of the old [**`shader_manager`**][0], which we could use as a starting point.
* There's a legacy [**`example`**] of its usage; however, the API should change in order to have a cleaner and easier to use API. Notice in this example that the renderer is requesting the shaders that it might use. However, the role will likely be swapped, as the materials are going to be the ones that have a specific shader according to its shading model.

[0]: <https://github.com/wpumacay/loco_renderer/blob/legacy/legacy/include/shaders/CShaderManager.h> (reference-impl-1)
[1]: <https://github.com/wpumacay/loco_renderer/blob/legacy/legacy/src/renderers/CMeshRenderer.cpp#L9> (reference-sample-usage-1)
